menu:
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'courses', url: '/courses'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/JeongjinLee88'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/JeongjinLee88'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

contacts:
- {name: 'Jeongjin Lee', title: 'Postdoc', institution: 'naXys-Unamur and UCLouvain', institution_address: 'Rue Joseph Grafe 2 5000 Namur', email: 'stecophil88@gmail.com', office: 'Faculty of Sciences 365', image: 'assets/img/contact.jpg'}
